Forja/urls.py
from django.contrib import admin
from django.urls import path
from ForjaApp import views
from django.conf.urls import handler404
from ForjaApp.views import submit_feedback,cinema_list,rate_cinema  # Import the view


urlpatterns = [path('', views.index, name='index'),
    path('admin/', admin.site.urls),  
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),     
    path('profile/', views.profile, name='profile'),
    path('recommend-similar/', views.recommend_similar_movies, name='recommend_similar_movies'),
    path('generate-image/', views.generate_image, name='generate_image'),
    path('movie-ending/', views.movie_ending_view, name='movie_ending'),
    path('song-writer/', views.song_writer_view, name='song_writer'),
    path('submit-feedback/', views.submit_feedback, name='submit_feedback'),
    path('user-feedback/', views.user_feedback_management, name='user_feedback_management'),
    path('movies/', views.movie_list, name='movie_list'),
    path('rate/<int:movie_id>/', views.rate_movie, name='rate_movie'),
     path('cinemas/', cinema_list, name='cinema_list'),
    path('cinemas/rate/<int:cinema_id>/', rate_cinema, name='rate_cinema'),

]

ForjaApp/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=200)
    release_date = models.DateField()
    overview = models.TextField(blank=True, default='')  # Ajoute `blank=True` et `default=''`
    poster_path = models.CharField(max_length=200, blank=True)


    def __str__(self):
        return self.title


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    score = models.IntegerField()  # Score sur 5
    review = models.TextField(blank=True, null=True)
    date_rated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.movie.title} - {self.score}"

class Recommendation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    similar_movies = models.JSONField()  # Pour stocker les informations des films similaires

    def __str__(self):
        return f"Recommendation for {self.user.username} based on {self.movie.title}"

class ArtisticDescription(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return f"Description for {self.movie.title}"



class UserFeedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recommendation = models.ForeignKey(Recommendation, on_delete=models.CASCADE)
    feedback_text = models.TextField()
    rating = models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Feedback from {self.user.username} on {self.recommendation.movie.title}"

class WatchLater(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'movie')  

    def __str__(self):
        return f"{self.user.username} - Watch Later - {self.movie.title}"
    
# models.py
from django.db import models

class Cinema(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()  # Ensure this field is present
    location = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class CinemaRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cinema = models.ForeignKey(Cinema, on_delete=models.CASCADE)
    score = models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])
    review = models.TextField(blank=True, null=True)
    date_rated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.cinema.name} - {self.score} étoiles"
    
    

ForjaApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Rating,CinemaRating

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['score', 'review']
        widgets = {
            'score': forms.NumberInput(attrs={'min': 1, 'max': 5}),
            'review': forms.Textarea(attrs={'placeholder': 'Write your review...'}),
        }
        
class CinemaRatingForm(forms.ModelForm):
    class Meta:
        model = CinemaRating
        fields = ['score', 'review']  # Fields you want the user to fill out
        widgets = {
            'review': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write your review here...'}),
        }        
        

ForjaApp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegisterForm,RatingForm,CinemaRatingForm
from django.contrib.auth.decorators import login_required
from .utils import get_similar_movies
from .models import Movie, Recommendation,UserFeedback,Rating,WatchLater,Cinema,CinemaRating
import re,requests,random,openai
from django.http import JsonResponse
from groq import Groq
import os
from django.conf import settings
from django.db.models import Avg


#import numpy as np
#from sklearn.metrics.pairwise import cosine_similarity

client = Groq(api_key='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')
openai.api_key = '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'
openai.api_base = "https://api.groq.com/openai/v1"
API_KEY = '89a4748b3788935d5e08221e4ed6f7ef'
BASE_URL = 'https://suno-apiv2-eight.vercel.app'

def range_1_to_5():
    return range(1, 6)
def index(request):
    url = f'https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}&language=en-US&page=1'
    response = requests.get(url)
    movies = response.json().get('results', [])

    # Préparer l'URL de base des images
    image_base_url = 'https://image.tmdb.org/t/p/w500/'

    # Ajouter l'URL complète pour chaque image de film et calculer la note moyenne sur 2
    for movie in movies:
        movie['poster_url'] = image_base_url + movie.get('poster_path', '')
        movie['vote_average_div_2'] = movie['vote_average'] / 2

    context = {'movies': movies[:8], 'range_1_to_5': range(1, 6)}  # Limiter à 8 films
    return render(request, 'index.html', context)

# views.py


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Votre compte a été créé avec succès !')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Vous êtes connecté !')
                return redirect('index')
            else:
                messages.error(request, 'Nom d\'utilisateur ou mot de passe incorrect.')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    messages.success(request, 'Vous avez été déconnecté.')
    return redirect('login')

@login_required  # Ceci nécessite que l'utilisateur soit connecté
def profile(request):
    return render(request, 'profile.html', {'user': request.user})

from django.shortcuts import render

@login_required
def user_feedback_management(request):
    feedbacks = UserFeedback.objects.filter(user=request.user)

    if request.method == 'POST':
        # Traitement de l'édition
        if 'save' in request.POST:
            feedback_id = request.POST.get('save')
            feedback_text = request.POST.get(f'feedback_text_{feedback_id}')
            rating = request.POST.get(f'rating_{feedback_id}')
            feedback = get_object_or_404(UserFeedback, id=feedback_id, user=request.user)
            feedback.feedback_text = feedback_text
            feedback.rating = rating
            feedback.save()

        # Traitement de la suppression
        elif 'delete' in request.POST:
            feedback_id = request.POST.get('delete')
            feedback = get_object_or_404(UserFeedback, id=feedback_id, user=request.user)
            feedback.delete()

        return redirect('user_feedback_management')  # Redirection après modification ou suppression

    return render(request, 'user_feedback_management.html', {
        'feedbacks': feedbacks
    })
@login_required
def recommend_similar_movies(request):
    similar_movies = []
    movie_title = ""
    recommendation = None  # Initialiser la variable recommendation

    if request.method == 'POST':
        movie_title = request.POST.get('movie_title')

        # Obtenir les films similaires à l'aide de l'algorithme optimisé
        similar_movies = get_similar_movies(movie_title)

        # Vérifier si le film est trouvé dans la base de données
        movie = Movie.objects.filter(title__icontains=movie_title).first()

        # Si le film n'est pas trouvé, l'ajouter à la base de données
        if not movie:
            # Utiliser le premier film similaire pour créer une nouvelle entrée de film
            if similar_movies:  # Vérifier qu'il y a des films similaires
                movie_data = similar_movies[0]  # Prenons le premier film similaire

                # Créer une nouvelle instance de Movie
                movie = Movie(
                    title=movie_data['title'],
                    release_date=movie_data['release_date'],
                    overview=movie_data['overview'],
                    poster_path=movie_data['poster_path']
                )
                movie.save()  # Sauvegarder le nouveau film dans la base de données

        # Si le film est trouvé ou a été ajouté, enregistrer la recommandation
        if movie:
            recommendation = Recommendation.objects.create(
                user=request.user,
                movie=movie,
                similar_movies=[{"title": m['title'], "id": m['id']} for m in similar_movies]  # Enregistrer les titres et IDs des films similaires
            )

        return render(request, 'recommendations.html', {'similar_movies': similar_movies, 'movie_title': movie_title, 'recommendation': recommendation})

    return render(request, 'recommendations.html', {'similar_movies': similar_movies, 'movie_title': movie_title, 'recommendation': recommendation})

def generate_image(request):

    image_url = None
    error_message = None

    if request.method == 'POST':
        description = request.POST.get('description')
        selected_style = request.POST.get('style')  # Récupérer le style sélectionné

        # Liste de mots-clés associés aux films
        movie_keywords = [
            'film', 'movie', 'character', 'plot', 'scene', 'actor', 
            'actress', 'director', 'genre', 'cinema', 'trailer'
        ]

        # Vérifier si la description contient des mots-clés de film
        if any(re.search(r'\b' + keyword + r'\b', description, re.IGNORECASE) for keyword in movie_keywords):
            # Ajouter le style de dessin à la description
            modified_description = f"{description}, {selected_style}"
            image_url = f"https://image.pollinations.ai/prompt/{modified_description}"
        else:
            error_message = "Veuillez entrer une description liée aux films ou personnages de films."

    return render(request, 'image_generator.html', {'image_url': image_url, 'error_message': error_message})

def generate_text(prompt):
    """Use Groq AI to generate a response based on a user prompt."""
    response = client.chat.completions.create(
        messages=[{"role": "user", "content": prompt}],
        model="llama3-8b-8192"
    )
    return response.choices[0].message.content.strip()

def text_to_speech(text):
    """Convert the given text to speech using Deepgram."""
    max_length = 2000
    if len(text) > max_length:
        text = text[:max_length]  # Truncate text to max_length characters

    url = "https://api.deepgram.com/v1/speak?model=aura-asteria-en"
    headers = {
        "Authorization": f"Token {'76dcd77db53a7659884675d0bfbad83679d5ab1f'}",
        "Content-Type": "application/json",
    }
    payload = {"text": text}

    response = requests.post(url, json=payload, headers=headers)

    print(f"Response Status Code: {response.status_code}")
    print(f"Response Body: {response.text}")

    if response.status_code == 200:
        return response.content  # Return audio bytes
    else:
        raise Exception(f"Failed to generate speech: {response.status_code}, {response.text}")






def movie_ending_view(request):
    """Handle user requests for custom movie endings."""
    if request.method == "POST":
        prompt = request.POST.get('prompt', "Imagine a new ending for Inception.")

        # Generate movie ending using Groq AI
        generated_text = generate_text(prompt)

        # Convert the generated text to speech
        audio_content = text_to_speech(generated_text)

        # Ensure the static directory exists
        static_dir = os.path.join(settings.BASE_DIR, "ForjaApp", "static")
        os.makedirs(static_dir, exist_ok=True)

        # Save the audio content to a file
        audio_file_path = os.path.join(static_dir, "generated_audio.mp3")
        with open(audio_file_path, "wb") as f:
            f.write(audio_content)

        return render(request, "movie_ending.html", {
            "generated_text": generated_text,
            "audio_path": f"{settings.STATIC_URL}generated_audio.mp3"  # Use STATIC_URL to construct the path
        })

    return render(request, "movie_ending.html")

def generate_audio_by_prompt(prompt):
    """Send prompt to the Vercel API to generate audio."""
    url = f"{BASE_URL}/api/generate"
    payload = {
        "prompt": prompt,
        "make_instrumental": False,
        "wait_audio": True  # Synchronous generation
    }
    try:
        response = requests.post(url, json=payload, headers={'Content-Type': 'application/json'})
        response.raise_for_status()  # Raise an exception for 4xx/5xx responses

ForjaApp/templates/add_genre.html
{% extends "base_generic.html" %}
{% load widget_tweaks %}

{% block content %}
<style>
    .login-wrapper {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        position: relative;
        z-index: 1;
    }

    .login-container {
        background-color: rgba(25, 26, 29, 0.8);
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.5);
        width: 400px;
        text-align: center;
        z-index: 10;
    }

    h2 {
        margin-bottom: 20px;
        color: #de1002;
    }

    .form-control {
        margin-bottom: 15px;
        padding: 10px;
        border: 1px solid #27292d;
        border-radius: 4px;
        color: #999!important;
        background: none;
    }

    .form-control:focus {
        box-shadow: none;
        border-color: #de1002;
    }

    button.btn-login {
        background: #de1002;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
        width: 100%;
    }

    button.btn-login:hover {
        background: #fff;
        color: #de1002;
    }

    ::placeholder {
        color: #999!important;
        opacity: 1;
    }
</style>

<div class="login-wrapper">
    <div class="login-container">
        <h2>Ajouter un Genre</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.name|add_class:"form-control" }}
            <button type="submit" class="btn-login">Ajouter le Genre</button>
        </form>
    </div>
</div>
{% endblock %}

ForjaApp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Forja</title>
    {% load static %}  
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/global.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani&display=swap" rel="stylesheet">
    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>

<section id="top">
<div class="container">
 <div class="row top_1">
  <div class="col-md-3">
   <div class="top_1l pt-1">
    <h3 class="mb-0"><a class="text-white" href="index.html"><i class="fa fa-video-camera col_red me-1"></i> Forja</a></h3>
   </div>
  </div>
  <div class="col-md-5">
   <div class="top_1m">
    <div class="input-group">
				<input type="text" class="form-control bg-black" placeholder="Search Site...">
				<span class="input-group-btn">
					<button class="btn btn text-white bg_red rounded-0 border-0" type="button">
						 Search</button>
				</span>
		</div>
   </div>
  </div>
  <div class="col-md-4">
   <div class="top_1r text-end">
     <ul class="social-network social-circle mb-0">
			<li><a href="#" class="icoRss" title="Rss"><i class="fa fa-instagram"></i></a></li>
			<li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
			<li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
			<li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-youtube"></i></a></li>
			<li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
		</ul>
   </div>
  </div>
 </div>
</div>
</section>

<section id="header">
	<nav class="navbar navbar-expand-md navbar-light" id="navbar_sticky">
	  <div class="container">
		<a class="navbar-brand text-white fw-bold" href="{% url 'index' %}"><i class="fa fa-video-camera col_red me-1"></i> Forja</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav mb-0">
			<li class="nav-item">
			  <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'generate_image' %}">Génération d'Image</a>
			</li>
	
			{% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'recommend_similar_movies' %}">Recommandation de Films</a>
              </li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'profile' %}">Profile</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'logout' %}">Déconnexion</a>
			</li>
			{% else %}
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'login' %}">Se connecter</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'register' %}">S'inscrire</a>
			</li>
			{% endif %}
		  </ul>
		</div>
	  </div>
	</nav>
	</section>
<div class="container">
    {% block content %}
    <!-- Contenu spécifique à chaque page -->
    {% endblock %}
</div>




<script>
window.onscroll = function() {myFunction()};

var navbar_sticky = document.getElementById("navbar_sticky");
var sticky = navbar_sticky.offsetTop;
var navbar_height = document.querySelector('.navbar').offsetHeight;

function myFunction() {
  if (window.pageYOffset >= sticky + navbar_height) {
    navbar_sticky.classList.add("sticky")
	document.body.style.paddingTop = navbar_height + 'px';
  } else {
    navbar_sticky.classList.remove("sticky");
	document.body.style.paddingTop = '0'
  }
}
</script>

</body>
<footer> <section id="footer">
	<div class="footer_m clearfix">
	 <div class="container">
	   <div class="row footer_1">
		<div class="col-md-4">
		 <div class="footer_1i">
		   <h3><a class="text-white" href="index.html"><i class="fa fa-video-camera col_red me-1"></i> Forja</a></h3>
		   <p class="mt-3">Lorem ipsum dolor sit amet consect etur adi pisicing elit sed do eiusmod tempor incididunt. Lorem ipsum dolor sit amet consect etur. </p>
		   <h6 class="fw-normal"><i class="fa fa-map-marker fs-5 align-middle col_red me-1"></i> 5311 Ceaver Sidge Td.
	Pakland, DE 13507</h6>
			<h6 class="fw-normal mt-3"><i class="fa fa-envelope fs-5 align-middle col_red me-1"></i> info@gmail.com</h6>
			<h6 class="fw-normal mt-3 mb-0"><i class="fa fa-phone fs-5 align-middle col_red me-1"></i>  +123 123 456</h6>
		 </div>
		</div>
		<div class="col-md-4">
		 <div class="footer_1i">
		  <h4>Flickr <span class="col_red">Stream</span></h4>
		  <div class="footer_1i1 row mt-4">
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/4.jpg' %}" height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/5.jpg' %}" height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/6.jpg' %}" height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/7.jpg' %}" height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		  </div>
		  <div class="footer_1i1 row mt-3">
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/8.jpg' %}" height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/9.jpg' %}" height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/10.jpg' %}" height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		   <div class="col-md-3 col-3">
			<div class="footer_1i1i">
			  <div class="grid clearfix">
					  <figure class="effect-jazz mb-0">
						<a href="#"><img src="{% static 'img/11.jpg' %} height="70" class="w-100" alt="abc"></a>
					  </figure>
				  </div>
			</div>
		   </div>
		  </div>
		 </div>
		</div>
		<div class="col-md-4">
		 <div class="footer_1i">
		  <h4>Sign  <span class="col_red">Newsletter</span></h4>
		  <p class="mt-3">Subscribe to our newsletter list to get latest news and updates from us</p>
		  <div class="input-group">
					<input type="text" class="form-control bg-black" placeholder="Email">
					<span class="input-group-btn">
						<button class="btn btn text-white bg_red rounded-0 border-0" type="button">
							 Subscribe</button>
					</span>
			</div>
			<ul class="social-network social-circle mb-0 mt-4">
				<li><a href="#" class="icoRss" title="Rss"><i class="fa fa-instagram"></i></a></li>
				<li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
				<li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
				<li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-youtube"></i></a></li>
				<li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
			</ul>
		 </div>
		</div>
	   </div>
	</div>
	</div>
	</section>
	
	<section id="footer_b" class="pt-3 pb-3 bg_grey">
	<div class="container">
	   <div class="row footer_1">
		 <div class="col-md-8">
		  <div class="footer_1l">
		   <p class="mb-0">© 2013 Your Website Name. All Rights Reserved | Design by <a class="col_red" href="http://www.templateonweb.com">TemplateOnWeb</a></p>
		  </div>
		 </div>
		 <div class="col-md-4">
		  <div class="footer_1r">
		   <ul class="mb-0">
			<li class="d-inline-block me-2"><a href="#">Home</a></li>
			<li class="d-inline-block me-2"><a href="#">Features</a></li>
			<li class="d-inline-block me-2"><a href="#">Pages</a></li>
			<li class="d-inline-block me-2"><a href="#">Portfolio</a></li>
			<li class="d-inline-block me-2"><a href="#">Blog</a></li>
			<li class="d-inline-block"><a href="#">Contact</a></li>
		   </ul>
		  </div>
		 </div>
	   </div>
	</div>
	</section></footer>
</html>

ForjaApp/templates/post_detail.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<section id="post-detail">
    <div class="container">
        <h1>{{ post.title }}</h1>
        <p>{{ post.content }}</p>
        <p>Posted by {{ post.author }} on {{ post.created_at }}</p>

        {% if user == post.author %}
            <a href="{% url 'post_update' post.id %}" class="btn btn-warning">Edit Post</a>
            <a href="{% url 'post_delete' post.id %}" class="btn btn-danger">Delete Post</a>
        {% endif %}

        <hr>

        <h2>Comments</h2>
        {% for comment in comments %}
            <div>
                <p><strong>{{ comment.author }}</strong> ({{ comment.created_at|date:"F j, Y, g:i a" }})</p>
                <p>{{ comment.content }}</p>
                {% if comment.author == request.user %}
                    <a href="{% url 'update_comment' comment.id %}">Edit</a>
                {% endif %}
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}

        <hr>

        <h3>Leave a Comment:</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Comment</button>
        </form>
    </div>
</section>
{% endblock %}

ForjaApp/templates/update_movie.html
{% extends 'base_generic.html' %}

{% block content %}
<h2>Edit Movie: {{ movie.title }}</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
        <label for="id_title">Title</label>
        {{ form.title }}
    </div>

    <div class="form-group">
        <label for="id_release_date">Release Date</label>
        {{ form.release_date }}
    </div>

    <div class="form-group">
        <label for="id_overview">Overview</label>
        {{ form.overview }}
    </div>

    <div class="form-group">
        <label for="id_poster_path">Poster Path</label>
        {{ form.poster_path }}
    </div>

    <div class="form-group">
        <label for="id_genres">Select Genres</label>
        {{ form.genres }}  <!-- Renders checkboxes for genres -->
    </div>

    <button type="submit">Update Movie</button>
</form>
<a href="{% url 'index' %}">Back to Movie List</a>
{% endblock %}